[www]
user = www-data
group = www-data

; TCP en vez del socket unix por defecto, porque Nginx y PHP-FPM viven en el
; mismo contenedor pero como procesos separados (manejados por supervisor).
listen = 127.0.0.1:9000

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4

catch_workers_output = yes
decorate_workers_output = no
